### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by bahaahassanieh** [moshekaplan/parse_nessus#1]
When running the parse_nessus.py script, I encountered the following error traceback:

python
Copy code
Traceback (most recent call last):
  File "C:\Users\bhh\PycharmProjects\nessus_parse\parse_nessus.py", line 68, in <module>
    main()
  File "C:\Users\bhh\PycharmProjects\nessus_parse\parse_nessus.py", line 26, in main
    writer.writeheader()
  File "C:\Users\bhh\AppData\Local\Programs\Python\Python39\lib\csv.py", line 143, in writeheader
    return self.writerow(header)
  File "C:\Users\bhh\AppData\Local\Programs\Python\Python39\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
TypeError: a bytes-like object is required, not 'str'
This error occurs in the csv.py module while attempting to write the header using the writeheader() method. It seems that the writeheader() method expects a bytes-like object, but it is receiving a string instead.

Steps to Reproduce:

Clone the repository or access the parse_nessus.py script.
Run the script using Python.
Observe the traceback error mentioned above.
Expected Behavior:
The writeheader() method should successfully write the header to the CSV file without raising a TypeError exception. The script should execute without any errors.

Additional Information:

Python version: 3.9
Operating System: Windows
Possible Solution:
One possible solution could be to ensure that the data passed to the writeheader() method is encoded as bytes before writing it. This can be achieved by using the encode() method on the string data.

I would be happy to contribute a fix for this issue once it is assigned to me.

**Comment by moshekaplan** [comment]
The failures is because this script was written for Python 2 and you're using Python 3. Running 2to3 might be the simplest fix. 

Honestly, this was a "write for a friend for a single use" sort of script, so while you're welcome to make your own changes, I don't have the time to support it.
